### ISSUE TITLE
Maven plugin issue for less to css comprassor

### ISSUE THREAD

**Issue by nchendu** [marceloverdijk/lesscss-maven-plugin#28]
[INFO] Compiling LESS source: accordion.less...
[ERROR] C:\myPrgosUI\ResponsiveTest\src\main\less\accordion.less [0:0]: Error compiling LESS source
org.lesscss.LessException: variable @baseLineHeight is undefined
    at org.lesscss.LessCompiler.compile(LessCompiler.java:283)
    at org.lesscss.LessCompiler.compile(LessCompiler.java:335)
    at org.lesscss.LessCompiler.compile(LessCompiler.java:359)
    at org.lesscss.mojo.CompileMojo.execute(CompileMojo.java:131)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.mozilla.javascript.JavaScriptException: [object Object](jar:file:/C:/Users/CHENDU/.m2/repository/org/lesscss/lesscss/1.3.3/lesscss-1.3.3.jar!/META-INF/less.js#8)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
    at org.lesscss.LessCompiler.compile(LessCompiler.java:270)
    ... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.266s
[INFO] Finished at: Sun Jun 16 16:41:15 IST 2013
[INFO] Final Memory: 9M/45M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.lesscss:lesscss-maven-plugin:1.3.3:compile (default) on project ResponsiveTest: Error while compiling LESS source: accordion.less: variable @baseLineHeight is undefined: [object Object](jar:file:/C:/Users/CHENDU/.m2/repository/org/lesscss/lesscss/1.3.3/lesscss-1.3.3.jar!/META-INF/less.js#8) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by shlomicthailand** [comment]
I have the same issue with variable which is defined in a separated file, and is included indirectly with the file being compiled.

**Comment by edgarleijs** [comment]
I have a similar problem. In my main.less I import e.g. variables.less, mixins.less and then the rest of the less files. Now I have to include my variables / mixins.less in every separate less file, wich will bloat my css file. I have around 30 less files to import!
